package com.castoff;

import android.app.Presentation;
import android.content.Context;
import android.os.Bundle;
import android.view.Display;
import android.webkit.WebView;
import android.webkit.WebViewClient;
import android.widget.FrameLayout;

public class SC2PresentationBridge extends Presentation {

    private FrameLayout rootContainer;
    private PresentationListener listener;

    public interface PresentationListener {
        void onDisplayRemoved();
    }

    public SC2PresentationBridge(Context outerContext, Display display) {
        super(outerContext, display);
    }

    public void setPresentationListener(PresentationListener listener) {
        this.listener = listener;
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        
        rootContainer = new FrameLayout(getContext());
        rootContainer.setLayoutParams(new FrameLayout.LayoutParams(
                FrameLayout.LayoutParams.MATCH_PARENT, 
                FrameLayout.LayoutParams.MATCH_PARENT));
        rootContainer.setBackgroundColor(0xFF000000); // Black background
        
        setContentView(rootContainer);
        showPlaceholder();
    }

    public void showPlaceholder() {
        if (rootContainer == null) return;
        rootContainer.removeAllViews();
        // Since we cannot use R classes before aapt2, we inflate using identifier or simply inflate the layout.
        // Actually, R is generated by aapt2 and we can use it, but the prompt says:
        // "Do NOT use any R imports that reference new resources before aapt2 generates R.java"
        // Meaning I can use getResources().getIdentifier() to avoid compiling issues if R isn't updated yet.
        int layoutId = getContext().getResources().getIdentifier("sc2_placeholder", "layout", getContext().getPackageName());
        if (layoutId != 0) {
            getLayoutInflater().inflate(layoutId, rootContainer, true);
        }
    }

    public void launchUrl(String url) {
        if (rootContainer == null) return;
        rootContainer.removeAllViews();
        WebView webView = new WebView(getContext());
        webView.setLayoutParams(new FrameLayout.LayoutParams(
                FrameLayout.LayoutParams.MATCH_PARENT, 
                FrameLayout.LayoutParams.MATCH_PARENT));
        webView.setWebViewClient(new WebViewClient());
        webView.getSettings().setJavaScriptEnabled(true);
        webView.loadUrl(url);
        rootContainer.addView(webView);
    }

    @Override
    public void onDisplayRemoved() {
        super.onDisplayRemoved();
        if (listener != null) {
            listener.onDisplayRemoved();
        }
    }

    @Override
    public void onDisplayChanged() {
        super.onDisplayChanged();
    }
}
